# Generated by Django 4.2.8 on 2023-12-21 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0004_position_remove_gps_lat_remove_gps_lon_gps_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='gps',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
